ALTER TABLE persona
  ADD COLUMN IF NOT EXISTS grado VARCHAR(100),
  ADD COLUMN IF NOT EXISTS peso DOUBLE,
  ADD COLUMN IF NOT EXISTS talla DOUBLE,
  ADD COLUMN IF NOT EXISTS imc DOUBLE,
  ADD COLUMN IF NOT EXISTS sexo VARCHAR(20);

ALTER TABLE persona
  ADD UNIQUE INDEX persona_dni_unique (dni);
